volumes:
  ingestion-volume-dag-airflow:
  ingestion-volume-dags:
  ingestion-volume-tmp:
  es-data:
  db-data-postgres:

services:
  postgresql:
    container_name: openmetadata_postgresql
    image: docker.getcollate.io/openmetadata/postgresql:1.12.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db-data-postgres:/var/lib/postgresql/data
      - ./docker/postgresql/postgres-script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net
    healthcheck:
      test: psql -U postgres -tAc 'select 1' -d openmetadata_db
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  elasticsearch:
    container_name: openmetadata_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: "curl -s http://localhost:9200/_cluster/health?pretty | grep status | grep -qE 'green|yellow' || exit 1"
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 90s
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - app_net

  execute-migrate-all:
    container_name: execute_migrate_all
    image: docker.getcollate.io/openmetadata/server:1.12.3
    command: "./bootstrap/openmetadata-ops.sh migrate"
    environment:
      DB_DRIVER_CLASS: org.postgresql.Driver
      DB_SCHEME: postgresql
      DB_PARAMS: allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: openmetadata_user
      DB_USER_PASSWORD: openmetadata_password
      OM_DATABASE: openmetadata_db
      ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    networks:
      - app_net

  openmetadata-server:
    container_name: openmetadata_server
    restart: always
    image: docker.getcollate.io/openmetadata/server:1.12.3
    environment:
      DB_DRIVER_CLASS: org.postgresql.Driver
      DB_SCHEME: postgresql
      DB_PARAMS: allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: openmetadata_user
      DB_USER_PASSWORD: openmetadata_password
      OM_DATABASE: openmetadata_db
      ELASTICSEARCH_HOST: elasticsearch
      PIPELINE_SERVICE_CLIENT_ENDPOINT: http://ingestion:8080
      SERVER_HOST_API_URL: http://openmetadata_server:8585/api      
    ports:
      - "8585:8585"
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      execute-migrate-all:
        condition: service_completed_successfully
    networks:
      - app_net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8586/healthcheck" ]

  ingestion:
    container_name: openmetadata_ingestion
    image: docker.getcollate.io/openmetadata/ingestion:1.12.3
    depends_on:
      postgresql:
        condition: service_healthy
      openmetadata-server:
        condition: service_started
    environment:
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      SERVER_HOST_API_URL: http://openmetadata_server:8585/api
      OPENMETADATA_SERVER_URL: http://openmetadata_server:8585
      DB_DRIVER_CLASS: org.postgresql.Driver
      DB_SCHEME: postgresql
      DB_PARAMS: allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      DB_HOST: postgresql
      DB_PORT: 5432
      AIRFLOW_DB: airflow_db
      DB_USER: airflow_user
      DB_PASSWORD: airflow_pass
    entrypoint: /bin/bash
    command: ["/opt/airflow/ingestion_dependency.sh"]
    ports:
      - "8080:8080"
    networks:
      - app_net
    volumes:
      - ingestion-volume-dag-airflow:/opt/airflow/dag_generated_configs
      - ingestion-volume-dags:/opt/airflow/dags
      - ingestion-volume-tmp:/tmp

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.240.0/24"